name: dio_oidc_interceptor_example
description: "Example to learn how using dio_oidc_interceptor."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dio_oidc_interceptor:
    path: ../
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  get_it: ^8.0.2
  injectable: ^2.5.0
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  flavor: ^2.0.0
  intl: ^0.19.0
  dio_mocked_responses: ^1.5.0+1
  flutter_svg: ^2.0.16
  characters: ^1.3.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  hive: ^2.2.3
  freezed_annotation: ^2.4.4
  transparent_image: ^2.0.1
  go_router: ^14.6.1
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.4+3
  flutter_highlighter: ^0.1.1
  septeo_design_system: ^0.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
  flutter_flavorizr: ^2.2.3
  bdd_widget_test: ^1.7.4
  freezed: ^2.5.7
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
